VIEW_LEN = 3
VIEW_AREA = VIEW_LEN * 2 + 1

EPOCHS = 200
SIM_COUNT = 20
full_game = 2500
FOOD_COUNT = 1

MINIBATCH_SIZE = full_game
MIN_REPLAY_MEMORY_SIZE = MINIBATCH_SIZE

DISCOUNT = 0.9
AGENT_LR = 0.0001
TRAIN_ALL = True
ALLOW_TRAIN = True
if TRAIN_ALL:
    REPLAY_MEMORY_SIZE = MINIBATCH_SIZE
else:
    REPLAY_MEMORY_SIZE = 5 * full_game * SIM_COUNT  # 10 full games 3k each

MODEL_NAME = f"Model21-4Actions-{TRAIN_ALL}--View-{VIEW_LEN}--B_{MINIBATCH_SIZE}-Lr{AGENT_LR}"


SAVE_PICS = ALLOW_TRAIN

STATE_OFFSET = 0
FIRST_EPS = 0.5
RAMP_EPS = 0.4
INITIAL_SMALL_EPS = 0.15
END_EPS = 0.0
EPS_INTERVAL = 10

SHOW_EVERY = 50
RENDER_DELAY = 0.01

LOAD_MODEL = True
FREE_MOVE = False
SHOW_LAST = False
PLOT_ALL_QS = True
PLOT_FIRST_QS = True
COMBINE_QS = True
SOUND_ALERT = True

TIMEOUT = 200
MOVE_PENALTY = -0.1
FOOD_REWARD = 50
FOOD_REWARD_RISING = False
DEAD_PENALTY = -50

